# Generated by Django 3.2.6 on 2021-08-06 10:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Labels',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requestId', models.UUIDField(editable=False)),
                ('labelNo', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Generated', 'Generated')], default='Open', max_length=15)),
                ('suppCode', models.CharField(max_length=3, unique=True)),
                ('suppName', models.CharField(max_length=100)),
                ('materialName', models.CharField(max_length=100)),
                ('materialSort', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=20)),
                ('fullBarchQty', models.IntegerField()),
                ('fullLabelsQty', models.IntegerField()),
                ('lastBatchQty', models.IntegerField()),
                ('lastLabelQty', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SuppSeq',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.IntegerField(default=21)),
                ('suppCode', models.CharField(max_length=3)),
                ('seq', models.IntegerField(default=0)),
            ],
            options={
                'unique_together': {('year', 'suppCode')},
            },
        ),
    ]
